MySite.MVC/Models/Components/LanguageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MySite.BL.Abstract;
using MySite.Entities.Entities.Concrete;

namespace MySite_MVC.Models.Components
{
    public class LanguageViewComponent : ViewComponent
    {
        private readonly IManager<Language> language;

        public LanguageViewComponent(IManager<Language> language)
        {
            this.language = language;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Bu bolum Daha sonra degistirilecek. Gelen Kullanicinin Role'une gore veriler cekilecek
            var languages = language.GetAll();
            return View(languages);
        }
    }
}

MySite.MVC/Models/Components/ProjectViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MySite.BL.Abstract;
using MySite.Entities.Entities.Concrete;

namespace MySite_MVC.Models.Components
{
    public class ProjectViewComponent : ViewComponent
    {
        private readonly IManager<Project> project;

        public ProjectViewComponent(IManager<Project> project)
        {
            this.project = project;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Bu bolum Daha sonra degistirilecek. Gelen Kullanicinin Role'une gore veriler cekilecek
            var projects = project.GetAll();
            return View(projects);
        }
    }
}

MySite.MVC/Models/Components/SkillViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MySite.BL.Abstract;
using MySite.Entities.Entities.Concrete;

namespace MySite_MVC.Models.Components
{
    public class SkillViewComponent : ViewComponent
    {
        private readonly IManager<Skill> skill;

        public SkillViewComponent(IManager<Skill> skill)
        {
            this.skill = skill;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Bu bolum Daha sonra degistirilecek. Gelen Kullanicinin Role'une gore veriler cekilecek
            var skills = skill.GetAll();
            return View(skills);
        }
    }
}

MySite.MVC/Models/Components/UserViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MySite.BL.Abstract;
using MySite.Entities.Entities.Concrete;

namespace MySite_MVC.Models.Components
{
    public class UserViewComponent : ViewComponent
    {
        private readonly IManager<User> user;

        public UserViewComponent(IManager<User> user)
        {
            this.user = user;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Bu bolum Daha sonra degistirilecek. Gelen Kullanicinin Role'une gore veriler cekilecek
            var users = user.GetAll();
            return View(users);
        }
    }
}

MySite.MVC/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MySite_MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var cookies = HttpContext.Request.Cookies;
            return View();
        }
    }
}

MySite.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MySite_MVC.Models;

namespace MySite_MVC.Controllers
{


    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(string page)
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //public IActionResult About()
        //{
        //    return View();
        //}
        //public IActionResult Activitie()
        //{
        //    return View();
        //}
        //public IActionResult Achievement()
        //{
        //    return View();
        //}
        //public IActionResult Education()
        //{
        //    return View();
        //}
        //public IActionResult Experience()
        //{
        //    return View();
        //}
        //public IActionResult Language()
        //{
        //    return View();
        //}
        //public IActionResult Project()
        //{
        //    return View();
        //}
        //public IActionResult Skill()
        //{
        //    return View();
        //}


    }
}

MySite.MVC/Areas/Admin/Views/Home/About.cshtml
 <!-- About-->
@await Component.InvokeAsync("User")

<hr class="m-0" />

MySite.MVC/Areas/Admin/Views/Home/Achievement.cshtml
<section class="resume-section" id="achievement">
    <div class="resume-section-content">
        @await Component.InvokeAsync("Achievement")
    </div>
</section>

MySite.MVC/Areas/Admin/Views/Home/Activitie.cshtml
<section class="resume-section" id="activitie">
    <div class="resume-section-content">
        @await Component.InvokeAsync("Activitie")
    </div>
</section>

MySite.MVC/Areas/Admin/Views/Home/CrudButtons.cshtml
@using MySite.Entities.Entities.Concrete
@model List<User>

<div class="input-group mb-3">
    <button class="btn btn-outline-secondary dropdown-toggle" 
            type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-gear-wide-connected"></i>
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-action="EditUser" asp-controller="User" asp-area="Admin" asp-route-id="@User.Identity"><i class="bi bi-pencil-square"> Edit</i></a></li>
        <li><a class="dropdown-item" asp-action="DeleteUser" asp-controller="User" asp-area="Admin" asp-route-id="@User.Identity"><i class="bi bi-archive"></i> Delete</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Separated link</a></li>
    </ul>

</div>

MySite.MVC/Areas/Admin/Views/Home/Education.cshtml
<section class="resume-section" id="education">
    <div class="resume-section-content">
        @await Component.InvokeAsync("Education")
    </div>
</section>

MySite.MVC/Areas/Admin/Views/Home/Experience.cshtml
<section class="resume-section" id="experience">
    <div class="resume-section-content">
        @await Component.InvokeAsync("Experience")

    </div>
</section>

MySite.MVC/Areas/Admin/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Resume - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">

    <partial name="_Navbar" />
    <!-- Page Content-->
    <div class="container-fluid p-0">
        <partial name="About" />
        <hr class="m-0" />
        <!-- Education-->
        <partial name="Education" />
        <hr class="m-0" />
        <!-- Experiance-->
        <partial name="Experience" />
        <hr class="m-0" />
        <!-- Project-->
        <partial name="Project" />
        <hr class="m-0" />
        <!-- Skills-->
        <partial name="Skill" />
        <hr class="m-0" />
        <!-- Language-->
        <partial name="Language" />
        <hr class="m-0" />
        <!-- Achievement-->
        <partial name="Achievement" />
        <hr class="m-0" />
        <!-- Activitie-->
        <partial name="Activitie" />
        <hr class="m-0" />

    </div>

    <hr class="m-0" />
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>

</body>
</html>

MySite.MVC/Areas/Admin/Views/Home/Language.cshtml
<section class="resume-section" id="language">
    <div class="resume-section-content">
        @await Component.InvokeAsync("Language")

    </div>
</section>

MySite.MVC/Areas/Admin/Views/Home/Project.cshtml
<section class="resume-section" id="project">
    <div class="resume-section-content">
        @await Component.InvokeAsync("Project")

    </div>
</section>

MySite.MVC/Areas/Admin/Views/Home/Skill.cshtml
<section class="resume-section" id="skill">
    <div class="resume-section-content">

        @await Component.InvokeAsync("Skill")
        @* <h2 class="mb-5">Skills</h2>
        <div class="subheading mb-3">Programming Languages & Tools</div>
        <ul class="list-inline dev-icons">
        <li class="list-inline-item"><i class="fab fa-html5"></i></li>
        <li class="list-inline-item"><i class="fab fa-css3-alt"></i></li>
        <li class="list-inline-item"><i class="fab fa-js-square"></i></li>
        <li class="list-inline-item"><i class="fab fa-angular"></i></li>
        <li class="list-inline-item"><i class="fab fa-react"></i></li>
        <li class="list-inline-item"><i class="fab fa-node-js"></i></li>
        <li class="list-inline-item"><i class="fab fa-sass"></i></li>
        <li class="list-inline-item"><i class="fab fa-less"></i></li>
        <li class="list-inline-item"><i class="fab fa-wordpress"></i></li>
        <li class="list-inline-item"><i class="fab fa-gulp"></i></li>
        <li class="list-inline-item"><i class="fab fa-grunt"></i></li>
        <li class="list-inline-item"><i class="fab fa-npm"></i></li>
        </ul>
        *@
    </div>
</section>